const express=require("express");
const router=express.Router();
const TController=require("../Controllers/tController");
const TourController=require("../Controllers/tourController.js");
const StudentController=require("../Controllers/studentController.js");
const CourseControler=require("../Controllers/courseController.js");
router.delete("/tours", TController.deleteTour);
router.put("/tours", TController.updateTour);
router.post("/tour",TourController.createTour);
router.post("/register",StudentController.createStudent);
router.post("/course",CourseControler.createCourse);
module.exports=router;
